# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
cz:
  languageCode: cs-cz
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Our project
  params:
    description: Site description in Chinese...
  menu:
    main:
      - name: En
        url: '#about'
        weight: 1
