main:
  - name: Demoš
    url: '#about'
    weight: 10
  - name: Postš
    url: '#posts'
    weight: 20
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Talks
    url: '#talks'
    weight: 40
  - name: Publications
    url: '#featured'
    weight: 50
  - name: Courses
    url: courses/
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70